### ISSUE TITLE
Dataset THEME not resolving

### ISSUE THREAD

**Issue by Metaduck** [idn-au/spatial-data#4]
Looking at Mutawintji - https://data.idnau.org/pid/nsw-ab/feature/1020 - the theme is given as - https://data.idnau.org/pid/vocab/urbanity/R - instead of "Remote". When the theme link is selected it returns a "Not Found" message with the URL being https://data.idnau.org/c/catalogs/pid:democat/pid:vocab/urbanity/R. I have spot checked five other features and they are all presenting the same issue.

**Comment by Metaduck** [comment]
https://data.idnau.org/c/catalogs is not responding

**Comment by lalewis1** [comment]
I've looked at the metadata for nsw-ab in the spatial-data repo and done a quick sparql query from data.idnau.org/sparql. the results suggest that the `urbanity.ttl` vocab has not been uploaded to the triple store.

@jamiefeiss I might need your help here as I don't have a visual on the upload process for the spatial data.

Potentially this is just something that we missed when we created the new vocab-data repo a few months ago

**Comment by lalewis1** [comment]
We Decide the fix is to just move this vocab to the vocab-data repo, as that is where it should be.

**Comment by lalewis1** [comment]
PR  #18 merged.  Remote / Rural Labels now appear properly.

However, link to definition for: https://data.idnau.org/pid/vocab/urbanity/R does not resolve to https://data.idnau.org/v/vocab/vcb:urbanity/rbnty:R like would be expected.

**Comment by lalewis1** [comment]
Fixed, Urbanity terms are now resolving properly.

For reference,

for prez to generate prezlinks for vocab terms each term must be a skos:concept* and declared as skos:inscheme to the parent skos:conceptscheme.

other classes may work. the class must be in the list of classes that an endpoint can return as given by the endpoint_classes variable here.
https://github.com/RDFLib/prez/blob/8b979dbf927cf00e5a0a170149377620c2f47786/prez/services/model_methods.py#L20
